Repository RPDJF/42-minishell, pull requests merged in 2024-04, with the labels that each got.

#18 Flow scheme
  docs/flow_scheme.drawio
  docs/flow_scheme.pdf
Labels: documentation

#19 Builtin commands fix norm issues
  cd
  src/builtin/cd.h
  src/builtin/echo.h
  src/env.c
  src/minishell.h
Labels: enhancement

#21 removed 42 header and some more work
  Makefile
  libs/betterft/src/ft_free_tab.c
  libs/betterft/src/ft_get_next_line.c
  libs/betterft/src/ft_strsjoin.c
  src/builtin/cd.c
  src/builtin/cd.h
  src/builtin/echo.c
  src/builtin/echo.h
  src/env.c
  src/env.h
  src/env/env.c
  src/env/env.h
  src/env/env_add.c
  src/env/env_conv.c
  src/env/env_destroy.c
  src/env/env_get.c
  src/executor.c
  src/executor.h
  src/lexer/lexer.c
  src/lexer/lexer.h
  src/lexer/lexer_lst_add.c
  src/lexer/lexer_quote.c
  src/main.c
  src/minishell.c
  src/minishell.h
  src/parsing/parsing.c
  src/parsing/parsing.h
  src/prompt.c
  src/prompt.h
  src/utils/binary_finder.c
  src/utils/binary_finder.h
  src/utils/exit_handler.c
  src/utils/exit_handler.h
  src/utils/lexer_bonus.c
  src/utils/lexer_utils.c
  src/utils/strr_realloc.c
Labels: enhancement

#22 Updated data-structure
  src/minishell.h
Labels: enhancement

#24 Executor
  Makefile
  src/builtin/builtin.h
  src/builtin/cd.c
  src/builtin/cd.h
  src/builtin/echo.h
  src/env/env.c
  src/env/env.h
  src/env/env_add.c
  src/env/env_conv.c
  src/env/env_get.c
  src/executor/executor.c
  src/executor/executor.h
  src/main.c
  src/minishell.c
  src/minishell.h
  src/prompt.c
  src/prompt.h
  src/utils/binary_finder.c
  src/utils/binary_finder.h
  src/utils/expand_words.c
  src/utils/expand_words.h
Labels: enhancement

#25 Executor - added minishell_history feature
  Makefile
  src/builtin/cd.c
  src/builtin/cd.h
  src/env/env.c
  src/env/env_add.c
  src/env/env_conv.c
  src/main.c
  src/minishell.c
  src/prompter/history.c
  src/prompter/history.h
  src/prompter/prompt.c
  src/prompter/prompt.h
Labels: enhancement

#26 Executor
  Makefile
  libs/betterft/Makefile
  libs/betterft/betterft.h
  libs/betterft/src/ft_strreplace_first.c
  src/executor/exec_child.c
  src/executor/exec_pipe.c
  src/executor/exec_redir.c
  src/executor/executor.c
  src/executor/executor.h
  src/minishell.h
  src/utils/binary_finder.c
  src/utils/exit_handler.c
  src/utils/exit_handler.h
  src/utils/expand_arr_words.c
  src/utils/expand_utils.c
  src/utils/expand_words.c
  src/utils/expand_words.h
Labels: enhancement

#27 Prompter bug fix wrong prompt when USER is unset
  src/prompter/prompt.c
Labels: bug fix

#29 Executor - improved error_msg() method
  src/utils/exit_handler.c
  src/utils/expand_words.c
Labels: enhancement

#30 Executor
  src/builtin/cd.c
  src/env/env.c
  src/env/env.h
  src/env/env_add.c
  src/env/env_conv.c
  src/env/env_destroy.c
  src/env/env_get.c
  src/executor/exec_child.c
  src/executor/exec_wexitstatus.c
  src/executor/executor.c
  src/executor/executor.h
  src/minishell.h
  src/utils/binary_finder.c
  src/utils/expand_words.c
Labels: enhancement

#32 Added a preview minishell build
  Makefile
  libs/betterft/betterft.h
  src/builtin/builtin.h
  src/builtin/cd.c
  src/builtin/cd.h
  src/builtin/echo.c
  src/builtin/echo.h
  src/builtin/exit.c
  src/builtin/exit.h
  src/builtin/export.c
  src/builtin/export.h
  src/builtin/pwd.c
  src/builtin/pwd.h
  src/env/env.c
  src/env/env.h
  src/env/env_add.c
  src/env/env_conv.c
  src/executor/exec_child.c
  src/executor/exec_pipe.c
  src/executor/exec_redir.c
  src/executor/executor.c
  src/executor/executor.h
  src/main_shitty_tokenizer.c
  src/prompter/here_doc.c
  src/prompter/here_doc.h
  src/prompter/prompt.c
  src/prompter/prompt.h
  src/utils/binary_finder.c
  src/utils/colors.h
  src/utils/exit_handler.c
  src/utils/exit_handler.h
Labels: enhancement, bug fix

#35 Fixed bug of the lexer.
  Makefile
  src/lexer/lexer.c
  src/lexer/lexer.h
  src/lexer/lexer_bonus.c
  src/lexer/lexer_lst_add.c
  src/lexer/lexer_quote.c
  src/lexer/lexer_utils.c
  src/main.c
  src/minishell.h
  src/parsing/parsing.c
  src/parsing/parsing.h
Labels: bug fix

#36 Merged t_builtin and t_cmd tokens
  libs/betterft/betterft.h
  src/executor/exec_child.c
  src/executor/exec_pipe.c
  src/executor/executor.c
  src/executor/executor.h
  src/main_shitty_tokenizer.c
  src/minishell.h
  src/utils/binary_finder.c
  src/utils/exit_handler.c
  src/utils/exit_handler.h
Labels: enhancement

#38 Executor
  Makefile
  src/builtin/builtin.c
  src/builtin/builtin.h
  src/builtin/envb.c
  src/builtin/envb.h
  src/builtin/export.h
  src/builtin/unset.c
  src/builtin/unset.h
  src/env/env.c
  src/env/env.h
  src/env/env_destroy.c
  src/executor/exec_child.c
  src/prompter/prompt.c
  src/utils/binary_finder.c
  src/utils/exit_handler.c
Labels: enhancement

#39 fixed bug for extended ascii, issue #37
  src/lexer/lexer.c
Labels: bug fix

#41 Added signals supports
  Makefile
  libs/betterft/betterft.h
  src/builtin/cd.c
  src/builtin/envb.c
  src/builtin/exit.c
  src/builtin/exit.h
  src/env/env_conv.c
  src/executor/exec_child.c
  src/executor/exec_signint.c
  src/executor/executor.c
  src/executor/executor.h
  src/main_shitty_tokenizer.c
  src/minishell.c
  src/minishell.h
  src/prompter/here_doc.c
  src/prompter/here_doc.h
  src/prompter/prompt.c
  src/signals/signals.c
  src/signals/signals.h
  src/utils/binary_finder.c
  src/utils/exit_handler.c
  src/utils/exit_handler.h
  src/utils/expand_words.c
Labels: enhancement

#43 Flow scheme
  docs/flow_scheme.drawio
  docs/flow_scheme.pdf
Labels: documentation

#44 Fixed bug issue #40
  src/lexer/lexer.c
  src/lexer/lexer.h
  src/lexer/lexer_quote.c
  src/lexer/lexer_utils.c
  src/main.c
  src/parsing/parsing.c
  src/parsing/parsing.h
Labels: bug fix

#45 Bug fixing
  src/main_shitty_tokenizer.c
  src/minishell.h
  src/prompter/prompt.h
  src/utils/exit_handler.c
Labels: enhancement, bug fix

#46 fix SHITTY_TOKENIZER
  src/main_shitty_tokenizer.c
Labels: bug fix

#48 Updated Makefile for MacOS
  Makefile
  src/executor/exec_child.c
  src/minishell.c
  src/minishell.h
  src/prompter/here_doc.c
  src/prompter/prompt.c
  src/utils/exit_handler.c
  src/utils/exit_handler.h
Labels: enhancement

#49 Fix Makefile for MacOS
  Makefile
Labels: bug fix

#50 Refactor file descriptor handling and pipe initialization
  src/executor/exec_child.c
  src/executor/exec_pipe.c
  src/executor/exec_redir.c
  src/executor/exec_signint.c
  src/executor/exec_wexitstatus.c
  src/executor/executor.c
  src/executor/executor.h
Labels: bug fix

#52 Flow scheme
  docs/flow_scheme.drawio
  docs/flow_scheme.pdf
Labels: documentation

#54 Bug fix and tokens now getting freed correctly
  src/builtin/cd.c
  src/env/env_conv.c
  src/executor/exec_destroy.c
  src/executor/executor.c
  src/executor/executor.h
Labels: enhancement, bug fix

#56 Fix pipes not getting correctly closed
  Makefile
  src/executor/exec_child.c
  src/executor/exec_destroy.c
  src/executor/exec_var_init.c
  src/executor/exec_wexitstatus.c
  src/executor/executor.c
  src/executor/executor.h
Labels: bug fix

#62 Update redirections var type
  src/builtin/exit.c
  src/env/env_add.c
  src/executor/exec_redir.c
  src/main_shitty_tokenizer.c
  src/prompter/prompt.c
Labels: bug fix

#64 add the first v1 of the tokeniser
  Makefile
  fdp
  src/lexer/lexer.c
  src/lexer/lexer.h
  src/lexer/lexer_lst_add.c
  src/lexer/lexer_quote.c
  src/lexer/lexer_utils.c
  src/main.c
  src/minishell.h
  src/parsing/free_exit_token.c
  src/parsing/parsing.c
  src/parsing/parsing.h
  src/parsing/parsing_utils.c
Labels: enhancement

#65 update and adding redirection output
  fdp
  src/main.c
  src/parsing/parsing.c
Labels: enhancement

#66 Fix here_doc not correcty closing on SIGINT
  Makefile
  src/env/env.h
  src/env/env_exitcode.c
  src/executor/executor.c
  src/main_shitty_tokenizer.c
  src/minishell.h
  src/prompter/here_doc.c
  src/prompter/prompt.c
  src/signals/signals.c
Labels: enhancement, bug fix

#71 Better context execution
  .gitignore
  Makefile
  src/executor/context.c
  src/executor/exec_child.c
  src/executor/exec_pipe.c
  src/executor/exec_redir.c
  src/executor/executor.c
  src/executor/executor.h
  src/main_shitty_tokenizer.c
  src/minishell.h
  src/utils/exit_handler.c
Labels: enhancement

#73 Experimental and or tokens execution (without parentheses)
  src/env/env.c
  src/executor/context.c
  src/executor/exec_utils.c
  src/executor/exec_wexitstatus.c
  src/executor/executor.c
  src/executor/executor.h
Labels: enhancement, bug fix

#76 Refactor token type from token_grp to token_subshell
  src/minishell.h
Labels: enhancement

#77 Update Flow scheme
  docs/flow_scheme.drawio
  docs/flow_scheme.pdf
Labels: documentation

#78 Fix issue fd not being properly closed
  src/executor/exec_child.c
  src/utils/exit_handler.c
Labels: enhancement, bug fix

#80 Bug fix
  src/executor/exec_var_init.c
  src/executor/executor.c
Labels: bug fix

#81 Add experimental subshell function and bug fixes
  Makefile
  libs/betterft/src/ft_strreplace_first.c
  src/executor/exec_redir.c
  src/executor/exec_subshell.c
  src/executor/exec_utils.c
  src/executor/exec_wexitstatus.c
  src/executor/executor.c
  src/executor/executor.h
  src/prompter/here_doc.c
  src/prompter/here_doc.h
  src/prompter/prompt.c
  src/signals/signals.c
  src/utils/expand_words.c
  src/utils/expand_words.h
Labels: enhancement, bug fix

#82 correct issue #79 and infinite loop
  src/lexer/lexer.h
  src/lexer/lexer_quote.c
  src/lexer/lexer_utils.c
  src/parsing/pars_quote_utils.c
  src/parsing/pars_t_var_init.c
  src/parsing/parsing.c
  src/parsing/parsing.h
  src/parsing/parsing_delem.c
  src/parsing/parsing_lst_add.c
Labels: bug fix

#83 Bug fixes and optimizations
  libs/betterft/Makefile
  libs/betterft/betterft.h
  libs/betterft/src/garbage_collector.c
  libs/betterft/src/garbage_collector_utils.c
  src/executor/exec_wexitstatus.c
  src/executor/executor.c
  src/prompter/history.c
Labels: bug fix

#87 Fix issues
  src/env/env.c
  src/executor/context.c
  src/executor/exec_child.c
  src/executor/exec_redir.c
  src/executor/exec_subshell.c
  src/executor/executor.c
  src/executor/executor.h
  src/main.c
  src/minishell.c
Labels: bug fix

#89 Bug fix and added default vars to minishell
  src/env/env.c
  src/executor/exec_subshell.c
  src/executor/executor.c
  src/utils/binary_finder.c
  src/utils/exit_handler.c
  src/utils/expand_words.c
Labels: enhancement, bug fix

#95 Executor
  .gitignore
  src/builtin/export.c
  src/env/env.c
  src/executor/context.c
  src/executor/exec_child.c
  src/executor/exec_redir.c
  src/executor/exec_subshell.c
  src/executor/exec_utils.c
  src/executor/exec_wexitstatus.c
  src/executor/executor.c
  src/executor/executor.h
  src/main.c
  src/minishell.c
  src/prompter/prompt.c
  src/signals/signals.c
  src/utils/exit_handler.c
  src/utils/expand_words.c
Labels: bug fix

#99 Bug fix
  Makefile
  libs/betterft/Makefile
  libs/betterft/betterft.h
  libs/betterft/src/ft_tablen.c
  src/executor/exec_child.c
  src/executor/exec_child_utils.c
  src/executor/exec_redir.c
  src/executor/exec_utils.c
  src/executor/executor.h
  src/utils/colors.h
  src/utils/exit_handler.c
Labels: bug fix

#100 Fix readline prompt
  src/env/env_add.c
  src/env/env_conv.c
  src/prompter/prompt.c
  src/prompter/prompt.h
  src/signals/signals.c
Labels: bug fix

#103 Fix double free in here_doc
  src/prompter/here_doc.c
Labels: bug fix
